apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.17.0
      helm:
        releaseName: cert-manager
        valueFiles:
          - $h8s/infrastructure/cert-manager/environments/prod/values.yaml
    - repoURL: https://github.com/fkheinstein204/k8s-ha-lab
      targetRevision: HEAD
      ref: h8s
    - repoURL: https://github.com/fkheinstein204/k8s-ha-lab
      targetRevision: HEAD
      path: infrastructure/cert-manager/environments/prod
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PruneLast=true
      - ServerSideApply=true